apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: atm
  labels:
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/part-of: atm
    apps.tanzu.vmware.com/has-tests: "true"  
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    networking.knative.dev/visibility: cluster-local
spec:
  params:
  - name: annotations
    value:
        autoscaling.knative.dev/minScale: "1"    
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
        prometheus.io/path: "/actuator/prometheus"    
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  source:
    git:
      url: https://github.com/tap-scenario-apps/atm-locator-backend
      ref:
        branch: main
    subPath: atm
 
