apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: atm-locator
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: atm-locator
    apis.apps.tanzu.vmware.com/register-api: "true"
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    apps.tanzu.vmware.com/has-tests: "true"  
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  params:
  - name: annotations
    value:
        autoscaling.knative.dev/minScale: "1"
  - name: api_descriptor
    value:
      type: openapi
      location: 
        path: "/api-docs"
      owner: atm
      system: atm
      description: ATM Locator API
  source:
    git:
      url: https://github.com/tap-scenario-apps/atm-locator-backend
      ref:
        branch: main
    subPath: atm-locator
